### ISSUE TITLE
Print integers with a "0x" prefix

### ISSUE THREAD

**Issue by soveran** [skx/simple.vm#15]
Hello @skx, thanks a lot for this great project!

I modified the `print_int` formatting string to include a `"0x"` prefix, and changed the padding to be four positions:

```diff
diff --git a/simple-vm-opcodes.c b/simple-vm-opcodes.c
index b284dc9..9edf3fb 100644
--- a/simple-vm-opcodes.c
+++ b/simple-vm-opcodes.c
@@ -343,7 +343,7 @@ void op_int_print(struct svm *svm)
     if (getenv("DEBUG") != NULL)
         printf("[STDOUT] Register R%02d => %d [Hex:%04x]\n", reg, val, val);
     else
-        printf("%02X", val);
+        printf("0x%04X", val);
 
 
     /* handle the next instruction */
```

The reason for the prefix is because it makes the base explicit, and the padding hints at the max value accepted for integers. I decided to use `"0x%04X"` instead of `"%#04X"` because I like the numbers in uppercase and the prefix in lowercase.

Do you think it could be a good change for simple.vm?

**Comment by soveran** [comment]
I think `"%#04x"` looks good to me too :-)

**Comment by skx** [comment]
I don't see a problem with that at all, thanks for the suggestion.

If you submit that change as a merge-request I'd be happy to accept it.  If not I'll copy&paste over the weekend.

Thanks for your interest.  This is just a demonstration, rather than a "real" project, but it's nice to see others interested so feature-suggestions, bug-reports, and contributions like this are certainly most welcome :)

**Comment by soveran** [comment]
Perfect, I just created the merge request. I think simple.vm can be a great tool for teaching. I will probably use it in a meetup to explain some concepts :-)
